config/routes.rb
Rails.application.routes.draw do
  
  devise_for :lecturers
  devise_for :classrepresentatives
  root 'person#index'

  get 'attendences/new'

  get 'person/supervisor'

  get 'person/classrepresentative'

  get 'person/lecturer'
  


































  resources :attendences
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
end

app/models/add_field_to_user.rb
class AddFieldToUser < ActiveRecord::Base
end

app/models/attendence.rb
class Attendence < ActiveRecord::Base
end

app/models/classrep.rb
class Classrep < ActiveRecord::Base
end

app/models/classrepresentative.rb
class Classrepresentative < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController
  before_action :set_attendence, only: [:show, :edit, :update, :destroy]

  # GET /attendences
  # GET /attendences.json
  def index
    @attendences = Attendence.all
  end

  # GET /attendences/1
  # GET /attendences/1.json
  def show
  end

  # GET /attendences/new
  def new
    @attendence = Attendence.new
  end

  # GET /attendences/1/edit
  def edit
  end

  # POST /attendences
  # POST /attendences.json
  def create
    @attendence = Attendence.new(attendence_params)

    respond_to do |format|
      if @attendence.save
        format.html { redirect_to @attendence, notice: 'Attendence was successfully created.' }
        format.json { render :show, status: :created, location: @attendence }
      else
        format.html { render :new }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendences/1
  # PATCH/PUT /attendences/1.json
  def update
    respond_to do |format|
      if @attendence.update(attendence_params)
        format.html { redirect_to @attendence, notice: 'Attendence was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendence }
      else
        format.html { render :edit }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendences/1
  # DELETE /attendences/1.json
  def destroy
    @attendence.destroy
    respond_to do |format|
      format.html { redirect_to attendences_url, notice: 'Attendence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendence
      @attendence = Attendence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendence_params
      params.require(:attendence).permit(:lecturer_id, :student_id, :course_id, :room_number)
    end
end

app/controllers/lecturer_controller.rb
class LecturerController < ActionController::Base
	def index
		
	end
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def index
  	
  end
  def supervisor
  end

  def classrepresentative
  end

  def lecturer
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/attendences/_form.html.erb
<%= form_for(@attendence) do |f| %>
  <% if @attendence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendence.errors.count, "error") %> prohibited this attendence from being saved:</h2>

      <ul>
      <% @attendence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lecturer_id %><br>
    <%= f.text_field :lecturer_id %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :room_number %><br>
    <%= f.text_field :room_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendences/edit.html.erb
<h1>Editing Attendence</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendence %> |
<%= link_to 'Back', attendences_path %>

app/views/attendences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attendences</h1>

<table>
  <thead>
    <tr>
      <th>Lecturer</th>
      <th>Student</th>
      <th>Course</th>
      <th>Room number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendences.each do |attendence| %>
      <tr>
        <td><%= attendence.lecturer_id %></td>
        <td><%= attendence.student_id %></td>
        <td><%= attendence.course_id %></td>
        <td><%= attendence.room_number %></td>
        <td><%= link_to 'Show', attendence %></td>
        <td><%= link_to 'Edit', edit_attendence_path(attendence) %></td>
        <td><%= link_to 'Destroy', attendence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendence', new_attendence_path %>

app/views/attendences/new.html.erb
<h1>New Attendence</h1>

<%= render 'form' %>

<%= link_to 'Back', attendences_path %>

app/views/attendences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lecturer:</strong>
  <%= @attendence.lecturer_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @attendence.student_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @attendence.course_id %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @attendence.room_number %>
</p>

<%= link_to 'Edit', edit_attendence_path(@attendence) %> |
<%= link_to 'Back', attendences_path %>

app/views/class_representative/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FollowUp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse" role="navigation">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">Follow App |</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-left">
				<li><%= link_to "Home",root_path%></li>
				<li><%= link_to "Supervisor",person_supervisor_path%></li>
				<li><%= link_to "Lecturer",person_lecturer_path%></li>
				<li><%= link_to "Checking In",attendences_new_path%></li>
				<li><%= link_to "Class Representative",person_classrepresentative_path%></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
						<li><%=link_to "Administrator", rails_admin_path%></li>
						
						
				<% if user_signed_in? %>	
						<li class="<%= 'active' if current_page?(destroy_user_session_path)%>"><%=link_to "signOut", destroy_user_session_path, method: :delete%></li>
				<%else%>
					<li class = "<%= 'active' if current_page?(new_user_session_path)%>"><%=link_to "signIn", new_user_session_path%></li>
					<li class = "<%= 'active' if current_page?(new_user_registration_path)%>"><%=link_to "SignUp", new_user_registration_path%></li>
						
				<%end%>

			</ul>
		</div>
	</nav>
	<%if notice%> 
	<p class="notice"><%=notice%></p>	
	<%end%>
	<p class="alert"><%=alert%></p>
<%= yield %>

</body>
</html>

app/views/lecturer/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/person/classrepresentative.html.erb
<h1>Classrepresentative</h1>

app/views/person/index.html.erb
<h1>Welcome to Our App</h1>

app/views/person/lecturer.html.erb
<h1>Person#lecturer</h1>
<p>Find me in app/views/person/lecturer.html.erb</p>

app/views/person/supervisor.html.erb
<h1>Person#supervisor</h1>
<p>Find me in app/views/person/supervisor.html.erb</p>

app/views/supervisor/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>